window.fullStateScores = {
	"Alabama": -10.50,
	"Alaska": 8.25,
	"American Samoa": 0.00,
	"Arizona": 7.50,
	"Arkansas": -12.25,
	"California": 45.00,
	"Colorado": 45.25,
	"Connecticut": 40.75,
	"Delaware": 30.25,
	"District of Columbia": 40.75,
	"Florida": -3.00,
	"Georgia": -1.00,
	"Guam": 4.75,
	"Hawaii": 31.25,
	"Idaho": -9.50,
	"Illinois": 43.00,
	"Indiana": -2.75,
	"Iowa": 6.50,
	"Kansas": 0.50,
	"Kentucky": 5.00,
	"Louisiana": -6.75,
	"Maine": 44.50,
	"Maryland": 42.00,
	"Massachusetts": 39,
	"Michigan": 30,
	"Minnesota": 36.75,
	"Mississippi": -7.50,
	"Missouri": -1.50,
	"Montana": -2.75,
	"Nebraska": 2.25,
	"Nevada": 41.25,
	"New Hampshire": 32.50,
	"New Jersey": 41.75,
	"New Mexico": 36.00,
	"New York": 44.50,
	"North Carolina": 7.25,
	"North Dakota": 9.50,
	"Northern Mariana Islands": 2.75,
	"Ohio": 2.25,
	"Oklahoma": -5.00,
	"Oregon": 37.50,
	"Pennsylvania": 16.75,
	"Puerto Rico": 19.75,
	"Rhode Island": 38.00,
	"South Carolina": -7.75,
	"South Dakota": -7.50,
	"Tennessee": -14.00,
	"Texas": -1.75,
	"U.S. Virgin Islands": 13.50,
	"Utah": 10.00,
	"Vermont": 38.50,
	"Virginia": 24.50,
	"Washington": 40.25,
	"West Virginia": -0.75,
	"Wisconsin": 17.75,
	"Wyoming": -6.00
};

window.stateAbbreviations = {
  "AL": "Alabama",
  "AK": "Alaska",
  "AS": "American Samoa",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "DC": "District of Columbia",
  "FL": "Florida",
  "GA": "Georgia",
  "GU": "Guam",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "MP": "Northern Mariana Islands",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "PR": "Puerto Rico",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "VI": "U.S. Virgin Islands",
  "UT": "Utah",
  "VT": "Vermont",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming"
};